openapi: 3.0.1

info:
  title: axpe-employees
  description: This API will provide information about employees working in the company Axpe Consulting S.L.
  version: '0.1.2'
  contact: 
    name: Daniel Velerdas Sedano
    email: daniel01velerdas@gmail.com

tags:
  - name: employees
    description: Refers to existing employees from the company

servers:
  - url: 'http://localhost:3000'

paths:
  '/employees':
    get:
      summary: Get a list of employees
      tags:
        - employees
      description: Employees Found
      operationId: get-employees
      parameters:
        - schema:
            type: string
            minLength: 1
          name: employeeName
          in: query
          required: false
          description: Filter for searching employees by name
          
        - schema:
            type: string
            minLength: 1
            pattern: '^(X(-|\.)?0?\d{7}(-|\.)?[A-Z]|[A-Z](-|\.)?\d{7}(-|\.)?[0-9A-Z]|\d{8}(-|\.)?[A-Z])|[A-z0-9]{2,3}[0-9]{6}$'
          name: identificationDocumentValue
          in: query
          required: false
          description: Filter for searching employees by NIF

        - schema:
            type: string
            minLength: 1
            enum:
              - TRAINEE
              - TEMPORAL
              - INDEFINITE
          name: contractStatus
          in: query
          required: false
          description: Filter for searching employees by contractual status

        - schema:
            type: string
            enum:
              - DEVELOPMENT
              - TESTING
              - DESIGN
              - MARKETING
              - MAINTENANCE
          name: department
          in: query
          required: false
          description: Filter for searching employees by department
        
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema: 
                type:  array
                items: {
                  $ref: '#/components/schemas/GetEmployees'
                }

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              examples:
                Invalid Parameters:
                  value:
                    code: invalidParameters
                    message: The parameters given are invalid
                    type: ERROR
                    description: The parameters given does not have the proper syntax.
        
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              examples:
                Employees Not Found:
                  value:
                    code: employeesNotFound
                    message: Employees with were not found
                    type: ERROR
                    description: Maybe there's no employees created yet.
                  
  
  '/employees/{employeeId}':
    parameters:
      - schema:
          type: integer
          format: uuid
        name: employeeId
        in: path
        required: true
        description: Id of an existing employee.
    
    get:
      summary: Get Employee Details by Employee Id
      tags: 
        - employees
      operationId: get-employees-employeeId
      description: Retrieve the information of the employee with the matching employee ID.
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetEmployee'
              examples:
                Get Employee Alice Smith:
                  value:
                    id: 123e4567-e89b-12d3-a456-426614174000
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    phoneNumber: +34 666 666 666
                    identificationDocument:
                      value: 12345678A
                      documentType: NIF
                    contractStatus: INDEFINITE
                    department: DEVELOPMENT
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              examples:
                Invalid Parameters:
                  value:
                    code: invalidParameters
                    message: The parameters given are invalid
                    type: ERROR
                    description: The parameters given does not have the proper syntax.
        
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              examples:
                Invalid parameters:
                  value:
                    code: employeeNotFound
                    message: Employee with given id was not found
                    type: ERROR
                    description: Maybe you misspelled the id of the employee or the employee does not exist.
            
    
    put:
      summary: Update Employee Information
      operationId: put-employees-employeeId
      tags:
        - employees
      responses:
        '204':
          description: No content
        
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              examples:
                Invalid Parameters:
                  value:
                    code: invalidParameters
                    message: The parameters given are invalid
                    type: ERROR
                    description: The parameters given does not have the proper syntax.  
        
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              examples:
                Invalid parameters:
                  value:
                    code: employeeNotFound
                    message: Employee with given id was not found
                    type: ERROR
                    description: Maybe you misspelled the id of the employee or the employee does not exist

      description: Update the information of an existing employee given the employee id.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostPutEmployee'

        description: Update all editable properties from existing employee.

    delete:
      summary: Delete an Employee
      operationId: delete-employee-employeeId
      tags:
        - employees
      description: Delete an existing employee.
      responses:
        '204':
          description: No content

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              examples:
                Invalid Parameters:
                  value:
                    code: invalidParameters
                    message: The parameters given are invalid
                    type: ERROR
                    description: The parameters given does not have the proper syntax.

        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              examples:
                Invalid parameters:
                  value:
                    code: employeeNotFound
                    message: Employee with given id was not found
                    type: ERROR
                    description: Try again, changing the parameters

  '/employee':
    post:
      summary: Create New Employee
      operationId: post-employee
      description: Create a new employee.
      tags: 
        - employees

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostPutEmployee'
        description: Post the necessary fields for the API to create a new employee.

      responses:
        '201':
          description: Created

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              examples:
                Invalid Parameters:
                  value:
                    code: invalidParameters
                    message: The parameters given are invalid
                    type: ERROR
                    description: This operation does not require any parameters.

components:
  schemas:
    GetEmployee:
      title: GetEmployee
      type: object
      description: Structure created to return an employee in a get operation.
      example:
        id: 123e4567-e89b-12d3-a456-426614174000
        firstName: Alice
        lastName: Smith
        email: alice.smith@gmail.com
        phoneNumber: +34 666 666 666
        identificationDocument: 
          value: 12345678A
          documentType: NIF
        department: DEVELOPMENT
        contractStatus: INDEFINITE
        dateOfBirth: '1997-10-31'
        emailVerified: true
        createDate: '2019-08-24'
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the given employee.
        firstName:
          type: string
          minLength: 1
          description: Name of the employee
        lastName:
          type: string
          minLength: 1
          description: Last names of the employee 
        email:
          type: string
          format: email
          description: Main email adress of the employee
        phoneNumber:
          type: string
          pattern: '^(\+34|0034|34)?[ -]*(6|7)[ -]*([0-9][ -]*){8}$'
          description: Main phone number of the employee
        identificationDocument:
          $ref: '#/components/schemas/IdentificationDocument'
        department:
          type: string
          description: Department of the company where the employee belongs to.
          enum:
            - DEVELOPMENT
            - TESTING
            - DESIGN
            - MARKETING
            - MAINTENANCE
        contractStatus:
          type: string
          description: Contractual status of the employee in the company. 
          enum:
            - TRAINEE
            - TEMPORAL
            - INDEFINITE
        dateOfBirth:
          type: string
          format: date
          description: Birthdate of the employee.
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the employee's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the employee was added to the system.
      required:
        - id
        - firstName
        - lastName
        - identificationDocument
        - contractStatus
        - email
        - emailVerified

    PostPutEmployee:
      title: PostEmployee
      type: object
      description: Structure created to create a new employee with a post operation or editing an existing one with a put operation.
      example:
        firstName: Alice
        lastName: Smith
        email: alice.smith@gmail.com
        phoneNumber: +34 666 666 666
        identificationDocument: 
          value: 12345678A
          documentType: NIF
        department: DEVELOPMENT
        contractStatus: INDEFINITE
        dateOfBirth: '1997-10-31'
      properties:
        firstName:
          type: string
          minLength: 1
          description: Name of the employee
        lastName:
          type: string
          minLength: 1
          description: Last names of the employee 
        email:
          type: string
          format: email
          description: Main email adress of the employee
        phoneNumber:
          type: string
          pattern: '^(\+34|0034|34)?[ -]*(6|7)[ -]*([0-9][ -]*){8}$'
          description: Main phone number of the employee
        identificationDocument:
          $ref: '#/components/schemas/IdentificationDocument'
        department:
          type: string
          description: Department of the company where the employee belongs to.
          enum:
            - DEVELOPMENT
            - TESTING
            - DESIGN
            - MARKETING
            - MAINTENANCE
        contractStatus:
          type: string
          description: Contractual status of the employee in the company. 
          enum:
            - TRAINEE
            - TEMPORAL
            - INDEFINITE
        dateOfBirth:
          type: string
          format: date
          description: Birthdate of the employee.
          example: '1997-10-31'
      required:
        - firstName
        - lastName
        - identificationDocument
        - email

    GetEmployees:
      title: GetEmployees
      type: array
      description: Structure created to return a list of employees in a get operation.
      items: {
        $ref: '#/components/schemas/GetEmployee'
      }
      example:
        - id: 123e4567-e89b-12d3-a456-426614174000
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          phoneNumber: +34 666 666 666
          identificationDocument: 
            value: 12345678A
            documentType: NIF
          department: DEVELOPMENT
          contractStatus: INDEFINITE
          dateOfBirth: '1997-10-31'
          emailVerified: true
          createDate: '2019-08-24'

        - id: 123f4567-e89a-12d3-a456-426614174000
          firstName: Bob
          lastName: Fellow
          email: bob.fellow@gmail.com
          phoneNumber: 666 66 66 67
          identificationDocument: 
            value: 12345678A
            documentType: NIF
          department: DEVELOPMENT
          contractStatus: INDEFINITE
          dateOfBirth: '1997-10-31'
          emailVerified: true
          createDate: '2019-08-24'

    IdentificationDocument:
      title: IdentificationDocument
      type: object
      description: Represents identification document information, showing the number and the type of document.
      properties:
        value:
          description: ''
          type: string
          pattern: '^(X(-|\.)?0?\d{7}(-|\.)?[A-Z]|[A-Z](-|\.)?\d{7}(-|\.)?[0-9A-Z]|\d{8}(-|\.)?[A-Z])|[A-z0-9]{2,3}[0-9]{6}$'
        documentType:
          description: ''
          type: string
          enum:
            - NIF
            - NIE
            - PASSPORT
      example:
        value: 12345678A
        documentType: NIF
      required:
        - value

    ErrorMessage:
      title: ErrorMessage
      type: object
      description: Object returned when an error happens
      properties:
        code: 
          type: string
          description: Field which briefly defines the problem
        message:
          type: string
          description: Message which describes the main issue
        type: 
          type: string
          description: Describes the type of message displayed
          enum:
            - ERROR
            - WARNING
            - INFO
        description:
          type: string
          description: Describes other details of the error
      example:
        code: invalidParameters
        message: There are invalid parameters in the request
        type: ERROR
        description: 'Address is not valid. Invalid character: ''@'''
      required:
        - code
        - message
        - type
